# Generated by Django 5.1.2 on 2024-10-20 23:36

import django.db.models.deletion
import posts.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок",
                        max_length=255,
                        validators=[posts.validators.validate_post_title],
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="Введите текст", verbose_name="Текст"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение, если оно есть",
                        null=True,
                        upload_to="posts/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата редактирования",
                        verbose_name="Дата редактирования",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Выберите автора",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "comment",
                    models.ManyToManyField(
                        help_text="Добавьте комментарии",
                        to="comments.comment",
                        verbose_name="Комментарии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
