# Generated by Django 5.1.2 on 2024-10-22 23:53

import django.db.models.deletion
import posts.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                help_text="Выберите автора",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                validators=[posts.validators.validate_author_age],
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="comment",
            field=models.ManyToManyField(
                blank=True,
                help_text="Добавьте комментарии",
                null=True,
                to="comments.comment",
                verbose_name="Комментарии",
            ),
        ),
    ]
