# Generated by Django 5.1.2 on 2024-10-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                help_text="Введите номер телефона в формате 999 123 45 67, +7 подставится автоматически",
                max_length=17,
                null=True,
                unique=True,
                verbose_name="телефон",
            ),
        ),
    ]
