# Generated by Django 5.1.2 on 2024-10-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                help_text="Введите вашу дату рождения",
                null=True,
                verbose_name="дата рождения",
            ),
        ),
    ]
