# Generated by Django 5.1.2 on 2024-10-22 23:53

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                help_text="Введите номер телефона в формате 999 123 45 67, +7 подставится автоматически",
                max_length=17,
                null=True,
                unique=True,
                validators=[users.validators.validate_phone],
                verbose_name="телефон",
            ),
        ),
    ]
